# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_abrule_cnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='abrule',
            options={'ordering': ('percentage',)},
        ),
        migrations.AlterModelOptions(
            name='creative',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='lineitem',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='creativepart',
            name='creatives',
            field=models.ManyToManyField(to='landing.Creative'),
        ),
    ]
