# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20170429_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativepart',
            name='creatives',
            field=models.ManyToManyField(blank=True, to='landing.Creative'),
        ),
    ]
