# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20170429_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativepart',
            name='executable',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
