# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20170430_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
