# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
