# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_page_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='purpose',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
