# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_page_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pages', models.ManyToManyField(to='landing.Page')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='creative',
            name='creativegroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landing.CreativeGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creativepart',
            name='creativegroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landing.CreativeGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landing.Host'),
            preserve_default=False,
        ),
    ]
