# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_auto_20170520_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('url', 'host')]),
        ),
    ]
